---
- hosts: all
  become: true

  tasks:
   # - name: Print All gather facts
    #  ansible.builtin.debug:
     #   var: ansible_facts


    - name: shutdown ubuntu only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian"
